[package]
name = "rust-udp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stream = { git = "ssh://git@github.com/Cube-OS/hal-stream.git"}